(SSS) C:\Users\405B\KFC>python main.py --type test --comment second_large_data --dataroot_dir ./data_large/
comment: second_large_data
model and loss plot -> ./model/model_second_large_data
Namespace(batch_size=100, beta1=0.5, beta2=0.999, comment='second_large_data', dataroot_dir='./data_large/', epoch=25, gpu_mode=True, lr=0.0002, num_workers=4, result_dir='./results/', sample_num=64, save_dir='./model/', type='test')
Average loss: 0.005773 Accuracy: 1283/1517 (84.574819)
error tracking
class 0: [125, 0, 4, 0, 5, 5, 6, 4, 16, 4]      accuracy: 73.964497(125/169)
class 1: [0, 156, 5, 1, 0, 0, 1, 3, 0, 7]       accuracy: 90.173410(156/173)
class 2: [0, 1, 107, 1, 0, 0, 6, 3, 0, 3]       accuracy: 88.429752(107/121)
class 3: [8, 6, 12, 121, 9, 4, 6, 3, 9, 12]     accuracy: 63.684211(121/190)
class 4: [3, 0, 0, 0, 158, 3, 3, 0, 0, 0]       accuracy: 94.610778(158/167)
class 5: [4, 0, 1, 2, 10, 98, 0, 0, 2, 0]       accuracy: 83.760684(98/117)
class 6: [4, 0, 7, 0, 5, 3, 136, 2, 0, 2]       accuracy: 85.534591(136/159)
class 7: [1, 3, 7, 0, 0, 0, 2, 119, 1, 1]       accuracy: 88.805970(119/134)
class 8: [2, 0, 2, 1, 2, 2, 3, 1, 130, 2]       accuracy: 89.655172(130/145)
class 9: [1, 1, 3, 2, 1, 0, 1, 0, 0, 133]       accuracy: 93.661972(133/142)
[*] Test finished